# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.40.2"
"rocks-config.nvim" = "3.0.0"
nvim-lspconfig = "1.0.0"
alpha-nvim = "scm"
"modicator.nvim" = "scm"
"noice.nvim" = "4.5.1"
"neoscroll.nvim" = "0.2.0"
"quicker.nvim" = "1.1.1"
nvim-comment = "scm"
nvim-autopairs = "scm"
nvim-cmp = "scm"
nvim-treesitter = "scm"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"
"plenary.nvim" = "scm"
nvim-dap = "0.8.0"
nvim-dap-ui = "4.0.0"
"conform.nvim" = "8.1.0"
"telescope.nvim" = "scm"
"toggleterm.nvim" = "2.12.0"
"vgit.nvim" = "0.2.3"
nvim-spectre = "scm"
"lazygit.nvim" = "scm"
"diffview.nvim" = "scm"
"nvim-tree.lua" = "1.6.0"
"indent-blankline.nvim" = "3.7.2"
"rocks-lazy.nvim" = "1.1.0"

[config]
plugins_dir = "modules/"
auto_setup = false

# language section
[plugins.nvim.treesitter]
config = "modules/lang/nvim_treesitter"
[bundles.nvim.dap]
items = ["nvim-dap", "nvim-dap-ui"]
config = "modules/lang/nvim_dap"
[plugins.conform.nvim]
config = "modules/lang/conform"

# completion section
[plugins.nvim.cmp]
config = "modules/completion/nvim_cmp"

# tools section
[plugins.telescope.nvim]
config = "modules/tools/telescope"
[plugins.toggleterm.nvim.config]
options = { shell = "bash" }

# ui section
[plugins.nvim-tree.lua]
config = "modules/ui/nvim_tree"



